import { pageMetadata } from "@/lib/site-metadata";
import StudioShell, { StudioNext } from "../components/StudioShell";
export const metadata = pageMetadata("/wer-wir-sind", "Wir sind Lilly & Piet | Satzstrategie", "Lilly ist Softwareentwicklerin, UX/UI-Designerin und KI-Spezialistin. Piet ist Inhaber und liefert den zweiten Blick. Lernen Sie Satzstrategie kennen.");
export default function StudioPage() {
  return <StudioShell active="/wer-wir-sind">
    <section className="about-hero"><h1><span>Lilly.</span><span className="about-amp" aria-hidden="true">&amp;</span><span>Piet.</span></h1><p>Zwei Menschen.<br />Eine gemeinsame Satzstrategie.</p></section>
    <section className="people-spread section-space" aria-label="Das Team"><article className="person-sheet person-lilly"><h2>Lilly</h2><p className="person-role"><span>Softwareentwicklerin</span><span>UX/UI-Designerin</span><span>KI-Spezialistin</span></p><p>Lilly sucht die Wörter, baut die Nutzerführung und entwickelt die Webseite. Sie verbindet den Gedanken hinter einem Angebot mit dem Auftritt, den Menschen sehen.</p><p>Sie steuert die KI-Agenten und prüft deren Ergebnisse vor der Freigabe.</p><p className="person-note">Vom ersten Wort<br />bis in den Code.</p></article><article className="person-sheet person-piet"><h2>Piet</h2><p className="person-role">Inhaber · Der zweite Blick</p><p>Piet arbeitet im Hintergrund. Er liest mit, hinterfragt Entwürfe und sagt, wo etwas noch nicht überzeugt.</p><p>Dieser zweite Blick gehört zu unserer Arbeit. Denn ein Satz muss auch für jemanden funktionieren, der ihn nicht selbst geschrieben hat.</p><p className="person-note">Noch einmal lesen.<br />Noch einmal fragen.</p></article></section>
    <section className="human-statement section-space"><h2>KI arbeitet mit.<br /><span>Wir entscheiden.</span></h2><div><p>Unsere Agenten unterstützen bei Recherche, Text und Code. Wir prüfen die Ergebnisse, überarbeiten und geben frei. Die Verantwortung bleibt bei uns.</p><p>Eine mögliche Formulierung ist schnell da. Ob sie zu Ihnen passt, was sie verspricht und wo sie stehen sollte, braucht einen genaueren Blick.</p></div></section>
    <StudioNext href="/kontakt" label="Direkter Kontakt mit Lilly.">Ein paar Zeilen reichen.</StudioNext>
  </StudioShell>;
}
